CREATE TABLE INVOICES_PAYMENTS(
    INVOICE_ID BIGINT NOT NULL,
    PAYMENTS_ID BIGINT NOT NULL
);

CREATE TABLE PAYMENTS(
    ID BIGINT auto_increment PRIMARY KEY,
    AMOUNT NUMERIC(19, 2),
    CREATION_DATE TIMESTAMP
);